/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbeans.pictionary;

/**
 *
 * @author sweetie
 */
public class derpderp extends javax.swing.JFrame {

    /**
     * Creates new form derpderp
     */
    public derpderp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        endLabel = new javax.swing.JLabel();
        team1PosEnd = new javax.swing.JPanel();
        team2PosEnd = new javax.swing.JPanel();
        diceBox = new javax.swing.JPanel();
        dieDescriptor = new javax.swing.JLabel();
        dieNumberLabel = new javax.swing.JLabel();
        rollButton = new javax.swing.JButton();
        teamNumberToRollLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.red);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(75, 75));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        endLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endLabel.setText("END");
        jPanel1.add(endLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 31, -1, -1));

        team1PosEnd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team1PosEnd.setMaximumSize(new java.awt.Dimension(25, 25));
        team1PosEnd.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team1PosEndLayout = new javax.swing.GroupLayout(team1PosEnd);
        team1PosEnd.setLayout(team1PosEndLayout);
        team1PosEndLayout.setHorizontalGroup(
            team1PosEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team1PosEndLayout.setVerticalGroup(
            team1PosEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel1.add(team1PosEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        team2PosEnd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team2PosEnd.setMaximumSize(new java.awt.Dimension(25, 25));
        team2PosEnd.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team2PosEndLayout = new javax.swing.GroupLayout(team2PosEnd);
        team2PosEnd.setLayout(team2PosEndLayout);
        team2PosEndLayout.setHorizontalGroup(
            team2PosEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team2PosEndLayout.setVerticalGroup(
            team2PosEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel1.add(team2PosEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        diceBox.setMaximumSize(new java.awt.Dimension(300, 200));
        diceBox.setMinimumSize(new java.awt.Dimension(300, 200));

        dieDescriptor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dieDescriptor.setText("Click the Roll button below to roll the die!");

        dieNumberLabel.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        dieNumberLabel.setText("6");

        rollButton.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        rollButton.setText("Roll!");
        rollButton.setToolTipText("Click me to Roll the Dice!");
        rollButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rollButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout diceBoxLayout = new javax.swing.GroupLayout(diceBox);
        diceBox.setLayout(diceBoxLayout);
        diceBoxLayout.setHorizontalGroup(
            diceBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diceBoxLayout.createSequentialGroup()
                .addComponent(dieDescriptor, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dieNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
            .addGroup(diceBoxLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(rollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diceBoxLayout.setVerticalGroup(
            diceBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diceBoxLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(diceBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dieDescriptor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dieNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(rollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        teamNumberToRollLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        teamNumberToRollLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teamNumberToRollLabel.setText("Team #, it's your turn to roll!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamNumberToRollLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(diceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teamNumberToRollLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(diceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rollButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rollButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(derpderp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(derpderp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(derpderp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(derpderp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new derpderp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel diceBox;
    private javax.swing.JLabel dieDescriptor;
    private javax.swing.JLabel dieNumberLabel;
    private javax.swing.JLabel endLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rollButton;
    private javax.swing.JPanel team1PosEnd;
    private javax.swing.JPanel team2PosEnd;
    private javax.swing.JLabel teamNumberToRollLabel;
    // End of variables declaration//GEN-END:variables
}
