/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbeans.pictionary;

/**
 *
 * @author sweetie
 */
public class GameWindow extends javax.swing.JFrame {

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        endLabel = new javax.swing.JLabel();
        team1PosEnd = new javax.swing.JPanel();
        team2PosEnd = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        team1Pos1 = new javax.swing.JPanel();
        team2Pos1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        team1Pos2 = new javax.swing.JPanel();
        team2Pos2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        team1Pos3 = new javax.swing.JPanel();
        team2Pos3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        team1Pos4 = new javax.swing.JPanel();
        team2Pos4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        team1Pos5 = new javax.swing.JPanel();
        team2Pos5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        team1Pos6 = new javax.swing.JPanel();
        team2Pos6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        team1Pos7 = new javax.swing.JPanel();
        team2Pos7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 750));

        jPanel1.setBackground(java.awt.Color.red);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(75, 75));
        jPanel1.setMinimumSize(new java.awt.Dimension(75, 75));
        jPanel1.setPreferredSize(new java.awt.Dimension(75, 75));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        endLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endLabel.setText("END");
        jPanel1.add(endLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 31, -1, -1));

        team1PosEnd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team1PosEnd.setMaximumSize(new java.awt.Dimension(25, 25));
        team1PosEnd.setMinimumSize(new java.awt.Dimension(25, 25));
        team1PosEnd.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team1PosEndLayout = new javax.swing.GroupLayout(team1PosEnd);
        team1PosEnd.setLayout(team1PosEndLayout);
        team1PosEndLayout.setHorizontalGroup(
            team1PosEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team1PosEndLayout.setVerticalGroup(
            team1PosEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel1.add(team1PosEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        team2PosEnd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team2PosEnd.setMaximumSize(new java.awt.Dimension(25, 25));
        team2PosEnd.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team2PosEndLayout = new javax.swing.GroupLayout(team2PosEnd);
        team2PosEnd.setLayout(team2PosEndLayout);
        team2PosEndLayout.setHorizontalGroup(
            team2PosEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team2PosEndLayout.setVerticalGroup(
            team2PosEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel1.add(team2PosEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(75, 75));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        team1Pos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team1Pos1.setMaximumSize(new java.awt.Dimension(25, 25));
        team1Pos1.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team1Pos1Layout = new javax.swing.GroupLayout(team1Pos1);
        team1Pos1.setLayout(team1Pos1Layout);
        team1Pos1Layout.setHorizontalGroup(
            team1Pos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team1Pos1Layout.setVerticalGroup(
            team1Pos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel2.add(team1Pos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        team2Pos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team2Pos1.setMaximumSize(new java.awt.Dimension(25, 25));
        team2Pos1.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team2Pos1Layout = new javax.swing.GroupLayout(team2Pos1);
        team2Pos1.setLayout(team2Pos1Layout);
        team2Pos1Layout.setHorizontalGroup(
            team2Pos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team2Pos1Layout.setVerticalGroup(
            team2Pos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel2.add(team2Pos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setMaximumSize(new java.awt.Dimension(75, 75));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        team1Pos2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team1Pos2.setMaximumSize(new java.awt.Dimension(25, 25));
        team1Pos2.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team1Pos2Layout = new javax.swing.GroupLayout(team1Pos2);
        team1Pos2.setLayout(team1Pos2Layout);
        team1Pos2Layout.setHorizontalGroup(
            team1Pos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team1Pos2Layout.setVerticalGroup(
            team1Pos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel3.add(team1Pos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        team2Pos2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team2Pos2.setMaximumSize(new java.awt.Dimension(25, 25));
        team2Pos2.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team2Pos2Layout = new javax.swing.GroupLayout(team2Pos2);
        team2Pos2.setLayout(team2Pos2Layout);
        team2Pos2Layout.setHorizontalGroup(
            team2Pos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team2Pos2Layout.setVerticalGroup(
            team2Pos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel3.add(team2Pos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setMaximumSize(new java.awt.Dimension(75, 75));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        team1Pos3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team1Pos3.setMaximumSize(new java.awt.Dimension(25, 25));
        team1Pos3.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team1Pos3Layout = new javax.swing.GroupLayout(team1Pos3);
        team1Pos3.setLayout(team1Pos3Layout);
        team1Pos3Layout.setHorizontalGroup(
            team1Pos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team1Pos3Layout.setVerticalGroup(
            team1Pos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel4.add(team1Pos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        team2Pos3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team2Pos3.setMaximumSize(new java.awt.Dimension(25, 25));
        team2Pos3.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team2Pos3Layout = new javax.swing.GroupLayout(team2Pos3);
        team2Pos3.setLayout(team2Pos3Layout);
        team2Pos3Layout.setHorizontalGroup(
            team2Pos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team2Pos3Layout.setVerticalGroup(
            team2Pos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel4.add(team2Pos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setMaximumSize(new java.awt.Dimension(75, 75));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        team1Pos4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team1Pos4.setMaximumSize(new java.awt.Dimension(25, 25));
        team1Pos4.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team1Pos4Layout = new javax.swing.GroupLayout(team1Pos4);
        team1Pos4.setLayout(team1Pos4Layout);
        team1Pos4Layout.setHorizontalGroup(
            team1Pos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team1Pos4Layout.setVerticalGroup(
            team1Pos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel5.add(team1Pos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        team2Pos4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team2Pos4.setMaximumSize(new java.awt.Dimension(25, 25));
        team2Pos4.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team2Pos4Layout = new javax.swing.GroupLayout(team2Pos4);
        team2Pos4.setLayout(team2Pos4Layout);
        team2Pos4Layout.setHorizontalGroup(
            team2Pos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team2Pos4Layout.setVerticalGroup(
            team2Pos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel5.add(team2Pos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setMaximumSize(new java.awt.Dimension(75, 75));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        team1Pos5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team1Pos5.setMaximumSize(new java.awt.Dimension(25, 25));
        team1Pos5.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team1Pos5Layout = new javax.swing.GroupLayout(team1Pos5);
        team1Pos5.setLayout(team1Pos5Layout);
        team1Pos5Layout.setHorizontalGroup(
            team1Pos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team1Pos5Layout.setVerticalGroup(
            team1Pos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel6.add(team1Pos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        team2Pos5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team2Pos5.setMaximumSize(new java.awt.Dimension(25, 25));
        team2Pos5.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team2Pos5Layout = new javax.swing.GroupLayout(team2Pos5);
        team2Pos5.setLayout(team2Pos5Layout);
        team2Pos5Layout.setHorizontalGroup(
            team2Pos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team2Pos5Layout.setVerticalGroup(
            team2Pos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel6.add(team2Pos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setMaximumSize(new java.awt.Dimension(75, 75));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        team1Pos6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team1Pos6.setMaximumSize(new java.awt.Dimension(25, 25));
        team1Pos6.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team1Pos6Layout = new javax.swing.GroupLayout(team1Pos6);
        team1Pos6.setLayout(team1Pos6Layout);
        team1Pos6Layout.setHorizontalGroup(
            team1Pos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team1Pos6Layout.setVerticalGroup(
            team1Pos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel7.add(team1Pos6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        team2Pos6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team2Pos6.setMaximumSize(new java.awt.Dimension(25, 25));
        team2Pos6.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team2Pos6Layout = new javax.swing.GroupLayout(team2Pos6);
        team2Pos6.setLayout(team2Pos6Layout);
        team2Pos6Layout.setHorizontalGroup(
            team2Pos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team2Pos6Layout.setVerticalGroup(
            team2Pos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel7.add(team2Pos6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setMaximumSize(new java.awt.Dimension(75, 75));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        team1Pos7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team1Pos7.setMaximumSize(new java.awt.Dimension(25, 25));
        team1Pos7.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team1Pos7Layout = new javax.swing.GroupLayout(team1Pos7);
        team1Pos7.setLayout(team1Pos7Layout);
        team1Pos7Layout.setHorizontalGroup(
            team1Pos7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team1Pos7Layout.setVerticalGroup(
            team1Pos7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel8.add(team1Pos7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        team2Pos7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team2Pos7.setMaximumSize(new java.awt.Dimension(25, 25));
        team2Pos7.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout team2Pos7Layout = new javax.swing.GroupLayout(team2Pos7);
        team2Pos7.setLayout(team2Pos7Layout);
        team2Pos7Layout.setHorizontalGroup(
            team2Pos7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        team2Pos7Layout.setVerticalGroup(
            team2Pos7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel8.add(team2Pos7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(484, 739, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(330, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel endLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel team1Pos1;
    private javax.swing.JPanel team1Pos2;
    private javax.swing.JPanel team1Pos3;
    private javax.swing.JPanel team1Pos4;
    private javax.swing.JPanel team1Pos5;
    private javax.swing.JPanel team1Pos6;
    private javax.swing.JPanel team1Pos7;
    private javax.swing.JPanel team1PosEnd;
    private javax.swing.JPanel team2Pos1;
    private javax.swing.JPanel team2Pos2;
    private javax.swing.JPanel team2Pos3;
    private javax.swing.JPanel team2Pos4;
    private javax.swing.JPanel team2Pos5;
    private javax.swing.JPanel team2Pos6;
    private javax.swing.JPanel team2Pos7;
    private javax.swing.JPanel team2PosEnd;
    // End of variables declaration//GEN-END:variables
}
