/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbeans.pictionary;

/**
 *
 * @author sweetie
 */
public class TeamAvatarSelection extends javax.swing.JPanel {

    /**
     * Creates new form TeamAvatarSelection
     */
    public TeamAvatarSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greenColour = new javax.swing.JPanel();
        blueColor = new javax.swing.JPanel();
        yellowColour = new javax.swing.JPanel();
        redColour = new javax.swing.JPanel();
        turquoiseColour = new javax.swing.JPanel();
        blackColour = new javax.swing.JPanel();
        whiteColour = new javax.swing.JPanel();
        purpleColour = new javax.swing.JPanel();
        teamNameLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();

        greenColour.setBackground(new java.awt.Color(0, 255, 0));
        greenColour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                greenColourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout greenColourLayout = new javax.swing.GroupLayout(greenColour);
        greenColour.setLayout(greenColourLayout);
        greenColourLayout.setHorizontalGroup(
            greenColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        greenColourLayout.setVerticalGroup(
            greenColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        blueColor.setBackground(new java.awt.Color(0, 0, 255));
        blueColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blueColorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout blueColorLayout = new javax.swing.GroupLayout(blueColor);
        blueColor.setLayout(blueColorLayout);
        blueColorLayout.setHorizontalGroup(
            blueColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        blueColorLayout.setVerticalGroup(
            blueColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        yellowColour.setBackground(new java.awt.Color(255, 255, 0));
        yellowColour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yellowColourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout yellowColourLayout = new javax.swing.GroupLayout(yellowColour);
        yellowColour.setLayout(yellowColourLayout);
        yellowColourLayout.setHorizontalGroup(
            yellowColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        yellowColourLayout.setVerticalGroup(
            yellowColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        redColour.setBackground(new java.awt.Color(255, 0, 0));
        redColour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redColourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout redColourLayout = new javax.swing.GroupLayout(redColour);
        redColour.setLayout(redColourLayout);
        redColourLayout.setHorizontalGroup(
            redColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        redColourLayout.setVerticalGroup(
            redColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        turquoiseColour.setBackground(new java.awt.Color(0, 0, 255));
        turquoiseColour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turquoiseColourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout turquoiseColourLayout = new javax.swing.GroupLayout(turquoiseColour);
        turquoiseColour.setLayout(turquoiseColourLayout);
        turquoiseColourLayout.setHorizontalGroup(
            turquoiseColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        turquoiseColourLayout.setVerticalGroup(
            turquoiseColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        blackColour.setBackground(new java.awt.Color(0, 0, 0));
        blackColour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blackColourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout blackColourLayout = new javax.swing.GroupLayout(blackColour);
        blackColour.setLayout(blackColourLayout);
        blackColourLayout.setHorizontalGroup(
            blackColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        blackColourLayout.setVerticalGroup(
            blackColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        whiteColour.setBackground(new java.awt.Color(255, 255, 255));
        whiteColour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whiteColourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout whiteColourLayout = new javax.swing.GroupLayout(whiteColour);
        whiteColour.setLayout(whiteColourLayout);
        whiteColourLayout.setHorizontalGroup(
            whiteColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        whiteColourLayout.setVerticalGroup(
            whiteColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        purpleColour.setBackground(new java.awt.Color(255, 0, 255));
        purpleColour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purpleColourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout purpleColourLayout = new javax.swing.GroupLayout(purpleColour);
        purpleColour.setLayout(purpleColourLayout);
        purpleColourLayout.setHorizontalGroup(
            purpleColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        purpleColourLayout.setVerticalGroup(
            purpleColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        teamNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        teamNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teamNameLabel.setText("Team 1, Select your icon!");
        teamNameLabel.setToolTipText("");

        confirmButton.setText("OK");
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(blackColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(whiteColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(greenColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yellowColour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purpleColour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(redColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turquoiseColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(teamNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(confirmButton)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(teamNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greenColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(turquoiseColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(purpleColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(blackColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whiteColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(confirmButton)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void blueColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueColorMouseClicked
        greenColour.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selected", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

    }//GEN-LAST:event_blueColorMouseClicked

    private void greenColourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenColourMouseClicked
        greenColour.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selected", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

    }//GEN-LAST:event_greenColourMouseClicked

    private void yellowColourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowColourMouseClicked
        greenColour.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selected", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

    }//GEN-LAST:event_yellowColourMouseClicked

    private void redColourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redColourMouseClicked
        greenColour.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selected", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

    }//GEN-LAST:event_redColourMouseClicked

    private void blackColourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blackColourMouseClicked
       greenColour.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selected", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

    }//GEN-LAST:event_blackColourMouseClicked

    private void whiteColourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whiteColourMouseClicked
        greenColour.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selected", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

    }//GEN-LAST:event_whiteColourMouseClicked

    private void purpleColourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purpleColourMouseClicked
        greenColour.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selected", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

    }//GEN-LAST:event_purpleColourMouseClicked

    private void turquoiseColourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turquoiseColourMouseClicked
        greenColour.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selected", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

    }//GEN-LAST:event_turquoiseColourMouseClicked

    private void confirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blackColour;
    private javax.swing.JPanel blueColor;
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel greenColour;
    private javax.swing.JPanel purpleColour;
    private javax.swing.JPanel redColour;
    private javax.swing.JLabel teamNameLabel;
    private javax.swing.JPanel turquoiseColour;
    private javax.swing.JPanel whiteColour;
    private javax.swing.JPanel yellowColour;
    // End of variables declaration//GEN-END:variables
}
